FROM ubuntu:16.10

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && \
    apt-get install \
                php-cli \
                php-curl \
                php-zip \
                php-xml \
                php-apcu \
                php-intl

